config/routes.rb
Rails.application.routes.draw do
  
  

  resources :microposts
  root 'static_pages#home'
  get '/about', to:'static_pages#about'
  get '/signup', to: 'users#new'
  post '/signup',to: 'users#create'
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'
  resources :users
  get '/posts',to: 'microposts#new'
  get '/search_all',to: 'microposts#index'
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def home
    end
    def about
    end
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<link href="https://fonts.googleapis.com/css?family=Short+Stack" rel="stylesheet">
<link href="assets/stylesheet/welcome.scss" rel="stylesheet" >
<style>
    .contain{
       
        margin: auto;
        padding: 20px;
        width: 900px;
        /*height: 1998px;*/
        border:20px;
        border-color:; #ffaa77;
        background-color:cornsilk;
        font-family: "Short Stack";
       
        
    }
    .bg-faded {
      background-color: palegoldenrod;
    }
    .card {
      position: relative;
      display: -ms-flexbox;
      display: flex;
      -ms-flex-direction: column;
      flex-direction: column;
      min-width: 0;
      word-wrap: break-word;
      /*background-color: gainsboro;*/ 
      background-clip: border-box;
      border: 1px solid rgba(0, 0, 0, 0.125);
      border-radius: 0.25rem;
      padding:20px;
    }
/*.card-img-overlay {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  padding: 1.25rem;
}*/
.bg-overlay {
  background-color: rgba(0, 0, 0, 0.7);
}
.tablebox{
    padding:20px;
}

</style>
<main class ="main-area">
    <div class = "card card-inverse">
          
         <h1 style="color:black"><b>ABOUT</b></h1>
        <table>
            <tr><ul>
                <tr><h3 style="color:black" ><b>MEMBER</b></h3></tr><br>
                <tr><td style="color:black;font-size: 120%;list-style-type:none"><li><b style="margin-left: 300px">Jirayu</b></li><td style="color:black;font-size: 120%"><b> Srisuk</b></td><td style="color:black;font-size: 120%"><b>&nbsp 5710520197</b></td></tr>
                <tr><td style="color:black;font-size: 120%;list-style-type:none"><li><b style="margin-left: 300px">Natchawi</b></li></td><td style="color:black;font-size: 120%"><b> Muangpa</b></td><td style="color:black;font-size: 120%"><b>&nbsp 5710520213</b></td></tr>
                <tr><td style="color:black;font-size: 120%;list-style-type:none"><li><b style="margin-left: 300px">Nonthicha</b></li></td><td style="color:black;font-size: 120%"><b> Suwansilsak</b></td><td style="color:black;font-size: 120%"><b>&nbsp 5810613439</b></td></tr>
                <tr><td style="color:black;font-size: 120%;list-style-type:none"><li><b style="margin-left: 300px">Varaporn</b></li></td><td style="color:black;font-size: 120%"><b> Ellermann</b></td><td style="color:black;font-size: 120%"><b>&nbsp 5910613354</b></td></tr>
            </ul></tr>
        </table>
        
        <article class = "Requirements" ><h3 style="color:black"><b>Requirement</b></h3>
        <p >
           <ul><li style="color:black;font-size: 120%;list-style-type:none"><b>1. มีระบบ Register สามารถสมัครสมาชิกเพื่อทำการ Login เพื่อมีสิทธิเข้าใช้งาน Web Application ได้​
                <br>
                2. มีระบบ Login เพื่อมีสิทธิเข้าใช้งาน Web Application ได้​
                <br>
                3. มีการเพิ่มข้อมูลต่างๆ เช่น สถานที่ซื้อ รุ่นของสินค้า ยี่ห้อของสินค้า และราคาของสินค้า​
                <br>
                4. สามารถอ่าน Post ได้​
                <br>
                5. มีที่เลือกอุปกรณ์ตามช่วงราคาที่ต้องการได้​
                <br>
                6. สามารถแก้ไข Post ที่ตนเอง Post ได้​
                <br>
                7. สามารถลบ Post ที่ตนเอง Post ได้​
                <br>
                8. Admin สามารถแก้ไข ลบ และอัพเดต Post ของทุกคนได้ ​
                <br>
                9. มีระบบ Logout เมื่อต้องการออกจากระบบ</b></li></ul>
        </p>
        </article>
        
        
        <article class = "Project proposal"><h3 style="color:black"><b>Project proposal</b></h3>
        <p>
            <ul style="color:black"><li style="list-style-type:none"><a href = "https://drive.google.com/file/d/1lNgTvK0JaW4ZvCnOb46-JfBmPuK0RDTd/view?usp=sharing" style="color:black;font-size: 120%" target="_blank"><b>Project proposal</b></a></li></ul>
        </p>
        </article>
        <article class = "ER-diagram"><h3 style="color:black"><b>ER-diagram</b></h3>
        <p>
            <%= image_tag("er.jpg", alt: "ER-diagram")%>
        </p>
        </article>
        
        <article class = "Tracker"><h3 style="color:black;"><b>Tracker</b></h3>
        <p>
            <ul style="color:black"><li style="list-style-type:none"><a href = "https://www.pivotaltracker.com/n/projects/2209354" style="color:black;font-size: 120%" target="_blank"><b>Pivotal Tracker</b></a></li></ul>
        </p>
        </article>
        
        <article class = "Bitbucket"><h3 style="color:black"><b>Bitbucket</b></h3>
        <p>
            <ul style="color:black"><li style="list-style-type:none"><a href = "https://bitbucket.org/softend/soften-myapp" style="color:black;font-size: 120%" target="_blank"><b>Bitbucket</b></a></li></ul>
        </p>
        </article>
        
        <article class = "YouTube"><h3 style="color:black"><b>YouTube</b></h3>
        <p>
            <ul style="color:black"><li style="list-style-type:none"><a href = "https://youtu.be/aux2W-ggVag" style="color:black;font-size: 120%" target="_blank"><b>Presentation</b></a></li></ul>
            <ul style="color:black"><li style="list-style-type:none"><a href = "https://youtu.be/cDlKKPNWu3U" style="color:black;font-size: 120%" target="_blank"><b>Final Presentation</b></a></li></ul>
        </p>
        </article>
        
        <article class = "Bitbucket"><h3 style="color:black"><b>Poster</b></h3><!--class??-->
        <p>
            <%= image_tag("Poster.png", alt: "poster")%>
        </p>
        </article>
        
        <article class = "UserStory"><h3 style="color:black"><b>UserStory</b></h3>
        <b>Iteration 1</b><br>
        <%= image_tag("1.png", alt: "feature1",width:'920',height:'396' )%>
        <br>
        <b>Iteration 2</b><br>
        <%= image_tag("2.png", alt: "feature4" ,width:'920',height:'728' )%>
        <br>
        
        <b>Iteration 3</b><br>
        <%= image_tag("3.png", alt: "feature9",width:'920',height:'449' )%>
        <br><br>
        </article>
        
           </div>
    </div>
</main>

app/views/static_pages/home.html.erb
<main class="main-area">
    
  <article style='color: red ;font-size:15px; font-weight: bold';>กรุณากรอกข้อมูลเป็นตัวเลขให้ถูกต้อง</article>
  <article class="test"><h3>ค้นหาราคาที่ต้องการ</h3></article>
 
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
        <%= form_tag microposts_path, :method => 'get' do %>
          <%= label_tag("ราคาเริ่มต้น") %><br>
          <%= number_field_tag :Starting_price, params[:Starting_price] ,:required => true, :min=>0, :size => "100" %><br>
          <%= label_tag("ราคาสูงสุด") %><br>
          <%= number_field_tag :Highest_price, params[:Highest_price] ,:required => true, :min=>0,:size => "100" %><br>
          <%= submit_tag("Search")%> 
          <% end %>
          <p><%= link_to "ค้นหาทั้งหมด",search_all_path %></p>
    </div>
  </div>
</main>



    
  


    
  