config/routes.rb
Rails.application.routes.draw do
  
  

  resources :microposts
  root 'static_pages#home'
  get '/about', to:'static_pages#about'
  get '/signup', to: 'users#new'
  post '/signup',to: 'users#create'
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'
  resources :users
  get '/posts',to: 'microposts#new'
  get '/search_all',to: 'microposts#index'
  
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :cpu, presence: true, length: { maximum: 255 }
  validates :detail_cpu, presence: true, length: { maximum: 255 }
  validates :mainboard, presence: true, length: { maximum: 255 }
  validates :detail_mainboard, presence: true, length: { maximum: 255 }
  validates :ram, presence: true, length: { maximum: 255 }
  validates :detail_ram, presence: true, length: { maximum: 255 }
  validates :storage, presence: true, length: { maximum: 255 }
  validates :detail_storage, presence: true, length: { maximum: 255 }
  validates :vga, presence: true, length: { maximum: 255 }
  validates :detail_vga, presence: true, length: { maximum: 255 }
  validates :power, presence: true, length: { maximum: 255 }
  validates :detail_power, presence: true, length: { maximum: 255 }
  validates :case, presence: true, length: { maximum: 255 }
  validates :detail_case, presence: true, length: { maximum: 255 }
  validates :price, presence: true, length: { maximum: 7 }
  
  def self.search(start,high)
    if start
      where("price >= ? and price <= ?",start,high)
    else
      all
    end
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:edit,:create, :destroy]
  before_action :admin_or_user, only: [:edit,:destroy]
  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.search(params[:Starting_price],params[:Highest_price])
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
     @microposts = Micropost.all
  end
  
  # GET /microposts/new
  def new
   # @micropost = current_user.microposts.build if logged_in?
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'The post was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'The post was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_path, notice: 'The post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:user_id, :cpu, :detail_cpu, :mainboard, :detail_mainboard, :ram, :detail_ram, :storage, :detail_storage, :vga, :detail_vga, :power, :detail_power, :case, :detail_case, :price)
    #params.require(:micropost).permit(:user_id, :cpu, :detail_cpu.:price_cpu, :mainboard, :detail_mainboard.:price_mainboard, :ram, :detail_ram.:price_ram, :storage, :detail_storage.:price_storage, :vga, :detail_vga.:price_vga, :power, :detail_power.:price_power, :case, :detail_case.:price_case,:price_cpu+:price_mainboard+:price_ram+:price_storage+:price_vga+:price_power+:price_case)
    end
    
    #def correct_user
    #  if !current_user.admin? 
    #    redirect_to root_url
    #  end
    #end
    
    def admin_or_user
      if logged_in? || current_user.admin?
      else
        redirect_to(root_url)
      end
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.erb
<main class="main-area">
<%= form_with(model: micropost, local: true) do |form| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



    <div class="row">
      <%= form.hidden_field :user_id, id: :micropost_user_id,value: current_user.id %>
    </div>
    
    
    
    <div class="form-row col-md-12" style="font-size:120%;">
        <div class="col-md-5 col-md-offset-1">
            <%= form.label :รุ่นของcpu %>
            <%= form.text_field :cpu, id: :micropost_cpu , class: 'form-control',:required => true ,placeholder: "กรุณากรอกชื่อรุ่นของอุปกรณ์..." %>
            <a href="#" rel="tooltip" title="intel corei7 7thgen"><i class="far fa-question-circle"></i></a>    
        </div>
          
      
        <div class="col-md-4 col-md-offset-0">
            <%= form.label :ราคาและสถานที่ซื้อสินค้า %>
            <%= form.text_field :detail_cpu, id: :micropost_detail_cpu, class: 'form-control',:required => true ,placeholder: "กรุณากรอกราคาและร้านค้าที่ขายสินค้านี้..." %>
            <a href="#" rel="tooltip" title="4950บาท jib future park rangsit"><i class="far fa-question-circle"></i></a>
        </div>
        
        
    </div>
    
    <div class="form-row col-md-12"style="font-size:120%;">
        <div class="col-md-5 col-md-offset-1">
            <%= form.label :รุ่นของmainboard %>
            <%= form.text_field :mainboard, id: :micropost_mainboard, class: 'form-control',:required => true ,placeholder: "กรุณากรอกชื่อรุ่นของอุปกรณ์..."%>
        </div>
      
        <div class="col-md-4 col-md-offset-0">
            <%= form.label :ราคาและสถานที่ซื้อสินค้า %>
            <%= form.text_field :detail_mainboard, id: :micropost_detail_mainboard, class: 'form-control',:required => true ,placeholder: "กรุณากรอกราคาและร้านค้าที่ขายสินค้านี้..."%>
        </div>
    </div> 
    
    <div class="form-row col-md-12"style="font-size:120%;">
        <div class="col-md-5 col-md-offset-1">
            <%= form.label :รุ่นของvga %>
            <%= form.text_field :vga, id: :micropost_vga, class: 'form-control',:required => true ,placeholder: "กรุณากรอกชื่อรุ่นของอุปกรณ์..."%>
        </div>
        
        <div class="col-md-4 col-md-offset-0">
            <%= form.label :ราคาและสถานที่ซื้อสินค้า %>
            <%= form.text_field :detail_vga, id: :micropost_detail_vga, class: 'form-control',:required => true ,placeholder: "กรุณากรอกราคาและร้านค้าที่ขายสินค้านี้..."%>
        </div>
    </div>
    
    <div class="form-row col-md-12"style="font-size:120%;">
        <div class="col-md-5 col-md-offset-1">
            <%= form.label :รุ่นของcase %>
        
            <%= form.text_field :case, id: :micropost_case, class: 'form-control',:required => true ,placeholder: "กรุณากรอกชื่อรุ่นของอุปกรณ์..."%>
        </div>
        
        <div class="col-md-4 col-md-offset-0">
            <%= form.label :ราคาและสถานที่ซื้อสินค้า %>
            <%= form.text_field :detail_case, id: :micropost_detail_case, class: 'form-control',:required => true ,placeholder: "กรุณากรอกราคาและร้านค้าที่ขายสินค้านี้..."%>
        </div>
    </div>
    
  
      <div class="form-row col-md-12" style="font-size:120%;">
        <div class="col-md-5 col-md-offset-1">
            <%= form.label :รุ่นของram %>
            <%= form.text_field :ram, id: :micropost_ram, class: 'form-control', class: 'form-control',:required => true ,placeholder: "กรุณากรอกชื่อรุ่นของอุปกรณ์..."%>
        </div>
        <div class="col-md-4 col-md-offset-0">
            <%= form.label :ราคาและสถานที่ซื้อสินค้า %>
            <%= form.text_field :detail_ram, id: :micropost_detail_ram, class: 'form-control',:required => true ,placeholder: "กรุณากรอกราคาและร้านค้าที่ขายสินค้านี้..."%>
        </div>
    </div>
    
    <div class="form-row col-md-12"style="font-size:120%;">
        <div class="col-md-5 col-md-offset-1">
            <%= form.label :รุ่นของpower %>
            <%= form.text_field :power, id: :micropost_power, class: 'form-control',:required => true ,placeholder: "กรุณากรอกชื่อรุ่นของอุปกรณ์..."%>
        </div>
        <div class="col-md-4 col-md-offset-0">
            <%= form.label :ราคาและสถานที่ซื้อสินค้า %>
            <%= form.text_field :detail_power, id: :micropost_detail_power, class: 'form-control',:required => true ,placeholder: "กรุณากรอกราคาและร้านค้าที่ขายสินค้านี้..."%>
        </div>
    </div>
    
    
    <div class="form-row col-md-12" style="font-size:120%;">
        <div class="col-md-5 col-md-offset-1">
          <%= form.label :รุ่นของstorage %>
            <%= form.text_field :storage, id: :micropost_storage, class: 'form-control',:required => true ,placeholder: "กรุณากรอกชื่อรุ่นของอุปกรณ์..."%>
        </div>
        <div class="col-md-4 col-md-offset-0">
              <%= form.label :ราคาและสถานที่ซื้อสินค้า %>
            <%= form.text_field :detail_storage, id: :micropost_detail_storage, class: 'form-control',:required => true ,placeholder: "กรุณากรอกราคาและร้านค้าที่ขายสินค้านี้..."%>
         </div>
    </div>
    
    <div class="form-row col-md-12" style="font-size:120%;">
        <div class="col-md-2 col-md-offset-5">
              <%= form.label :ราคารวม %>
            <%= form.number_field :price, id: :micropost_price, class: 'form-control',:required => true ,:min => 0 %>
        </div>
    </div>
    
    <div class="actions">
        <%= form.submit %><br>
    </div>
    
<% end %>
</main>

app/views/microposts/_form_price.html.erb
<main class="main-area">
<%= form_with(model: micropost, local: true) do |form| %>
  <% if micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



    <div class="row">
      <%= form.hidden_field :user_id, id: :micropost_user_id,value: current_user.id %>
    </div>
  
    <div class="form-row"style="font-size:120%;">
        <div class="col-md-5"style="margin=0; padding=0;">
            <%= form.label :รุ่นของcpu %>
            <%= form.text_field :cpu, id: :micropost_cpu , class: 'form-control',:required => true ,placeholder: "กรุณากรอกชื่อรุ่นของอุปกรณ์...", :required => true ,:value => 'intel corei7 7thgen'%>
        </div>
        <div class="col-md-2">
            <%= form.label :ราคา %> 
            <%= form.number_field :price_cpu, id: :micropost_price_cpu, class: 'form-control',:required => true,:min => 0 ,placeholder: "ราคา...", :required => true ,:value => '7000'%>
        </div>
        <div class="col-md-5">
            <%= form.label :สถานที่ซื้อสินค้า %>
            <%= form.text_field :detail_cpu, id: :micropost_detail_cpu, class: 'form-control',:required => true ,placeholder: "กรุณากรอกร้านค้าที่ขายสินค้านี้...",:required => true ,:value => 'jib future park rangsit'%>
        </div>
    </div>
    
    <div class="form-row"style="font-size:120%;">
        <div class="col-md-5 mb-5">
            <%= form.label :รุ่นของmainboard %>
            <%= form.text_field :mainboard, id: :micropost_mainboard, class: 'form-control',:required => true ,placeholder: "กรุณากรอกชื่อรุ่นของอุปกรณ์..."%>
        </div>
        <div class="col-md-2 mb-4">
            <%= form.label :ราคา %> 
            <%= form.number_field :price_mainboard, id: :micropost_price_mainboard, class: 'form-control',:required => true,:min => 0 ,placeholder: "ราคา"%>
        </div>
        <div class="col-md-5 mb-5">
            <%= form.label :สถานที่ซื้อสินค้า %>
            <%= form.text_field :detail_mainboard, id: :micropost_detail_mainboard, class: 'form-control',:required => true ,placeholder: "กรุณากรอกร้านค้าที่ขายสินค้านี้..."%>
        </div>
    </div> 
    
    <div class="form-row"style="font-size:120%;">
        <div class="col-md-5">
            <%= form.label :รุ่นของvga %>
            <%= form.text_field :vga, id: :micropost_vga, class: 'form-control',:required => true ,placeholder: "กรุณากรอกชื่อรุ่นของอุปกรณ์..."%>
        </div>
        <div class="col-md-2">
            <%= form.label :ราคา %> 
            <%= form.number_field :price_vga, id: :micropost_price_vga, class: 'form-control',:required => true,:min => 0 ,placeholder: "ราคา"%>
        </div>
        <div class="col-md-5">
            <%= form.label :สถานที่ซื้อสินค้า %>
            <%= form.text_field :detail_vga, id: :micropost_detail_vga, class: 'form-control',:required => true ,placeholder: "กรุณากรอกร้านค้าที่ขายสินค้านี้..."%>
        </div>
    </div>
    
    <div class="form-row"style="font-size:120%;">
        <div class="col-md-5">
            <%= form.label :รุ่นของcase %>
            <%= form.label :case %>
            <%= form.text_field :case, id: :micropost_case, class: 'form-control',:required => true ,placeholder: "กรุณากรอกชื่อรุ่นของอุปกรณ์..."%>
        </div>
        <div class="col-md-2 ">
            <%= form.label :ราคา %> 
            <%= form.number_field :price_case, id: :micropost_price_case, class: 'form-control',:required => true,:min => 0 ,placeholder: "ราคา"%>
        </div>
        <div class="col-md-5 ">
            <%= form.label :สถานที่ซื้อสินค้า %>
            <%= form.text_field :detail_case, id: :micropost_detail_case, class: 'form-control',:required => true ,placeholder: "กุรณากรอกร้านค้าที่ขายสินค้านี้..."%>
        </div>
    </div>
    
    <div class="form-row" style="font-size:120%;">
        <div class="col-md-4">
            <%= form.label :รุ่นของram %>
            <%= form.text_field :ram, id: :micropost_ram, class: 'form-control', class: 'form-control',:required => true ,placeholder: "กรุณากรอกชื่อรุ่นของอุปกรณ์..."%>
        </div>
        <div class="col-md-3">
            <!--style="border-radius: 15px 50px 30px 5px;"-->
            <%= form.label :ขนาดram %>
            <select id="ram_size" class="custom-select">
                <option value="" disabled = "disabled" selected="กรุณาเลือกขนาดแรม">กรุณาเลือกขนาด ram</option>
                <option value="2GB">2GB</option>
                <option value="4GB">4GB</option>
                <option value="8GB">8GB</option>
                <option value="16GB">16GB</option>
                <option value="32GB">32GB</option>
            </select>
        </div>    
        <div class="col-md-2">
            <%= form.label :ราคา %> 
            <%= form.number_field :price_ram, id: :micropost_price_ram, class: 'form-control',:required => true,:min => 0 ,placeholder: "ราคา"%>
        </div>
        <div class="col-md-3">
            <%= form.label :สถานที่ซื้อสินค้า %>
            <%= form.text_field :detail_ram, id: :micropost_detail_ram, class: 'form-control',:required => true ,placeholder: "กรุณากรอกร้านค้าที่ขายสินค้านี้..."%>
        </div>
    </div>
    
    <div class="form-row" style="font-size:120%;">
        <div class="col-md-4">
          <%= form.label :รุ่นของstorage %>
            <%= form.text_field :storage, id: :micropost_storage, class: 'form-control',:required => true ,placeholder: "กรุณากรอกชื่อรุ่นของอุปกรณ์..."%>
        </div>
        <div class="col-md-3">
             <%= form.label :ขนาดฮาร์ดดิสก์ %>
            <select class="custom-select">
                <option value="" disabled = "disabled" selected="กรุณาเลือกขนาดความจุฮาร์ดดิสต์" >กรุณาเลือกขนาดความจุฮาร์ดดิสต์</option>
                <option value="500GB">500GB</option>
                <option value="1TB">1TB</option>
                <option value="2TB">2TB</option>
                <option value="3TB">3TB</option>
                <option value="4TB">4TB</option>
                <option value="6TB">6TB</option>
                <option value="8TB">8TB</option>
                <option value="10TB">10TB</option>
                <option value="12TB">12TB</option>
                <option value="14TB">14TB</option>
            </select>
            </div>    
        <div class="col-md-2 ">
          <%= form.label :ราคา %> 
            <%= form.number_field :price_storage, id: :micropost_price_storage, class: 'form-control',:required => true,:min => 0 ,placeholder: "ราคา"%>
         </div>
        <div class="col-md-3 ">
              <%= form.label :สถานที่ซื้อสินค้า %>
            <%= form.text_field :detail_storage, id: :micropost_detail_storage, class: 'form-control',:required => true ,placeholder: "กรุณากรอกร้านค้าที่ขายสินค้านี้..."%>
         </div>
    </div>
    
    <div class="form-row"style="font-size:120%;">
        <div class="col-md-4">
            <%= form.label :รุ่นของpower %>
            <%= form.text_field :power, id: :micropost_power, class: 'form-control',:required => true ,placeholder: "กรุณากรอกชื่อรุ่นของอุปกรณ์..."%>
        </div>
        <div class="col-md-3" style="border=100%">
            <%= form.label :ขนาดกำลังไฟ %>
            <select class="custom-select">
                <option value="" disabled = "disabled" selected="กรุณาเลือกขนาดกำลังไฟ" >กรุณาเลือกขนาดกำลังไฟ</option>
                <option value="400W">400W</option>
                <option value="450W">450W</option>
                <option value="500W">500W</option>
                <option value="520W">520W</option>
                <option value="535W">535W</option>
                <option value="550W">550W</option>
                <option value="580W">580W</option>
                <option value="600W">600W</option>
                <option value="650W">650W</option>
                <option value="700W">700W</option>
                <option value="735W">735W</option>
                <option value="750W">750W</option>
                <option value="800W">800W</option>
                <option value="835W">835W</option>
                <option value="850W">850W</option>
                <option value="860W">860W</option>
                <option value="1000W">1000W</option>
                <option value="1100W">1100W</option>
                <option value="1200W">1200W</option>
            </select>
        </div> 
        <div class="col-md-2">
            <%= form.label :ราคา %> 
            <%= form.number_field :price_power, id: :micropost_price_power, class: 'form-control',:required => true,:min => 0 ,placeholder: "ราคา"%>
        </div>
        <div class="col-md-3">
            <%= form.label :สถานที่ซื้อสินค้า %>
            <%= form.text_field :detail_power, id: :micropost_detail_power, class: 'form-control',:required => true ,placeholder: "กรุณากรอกร้านค้าที่ขายสินค้านี้..."%>
        </div>
    </div>
    
    <div class="actions">
        <%= form.submit %>
    </div>
<% end %>
</main>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <!--<%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>-->
  <!--<span class="user"><%= link_to micropost.user.name, micropost.user %></span><br>-->

<div class="table-responsive-md">
<table class="table">
 
<tbody>
 <p><strong>ราคารวม :</strong><%= micropost.price %> บาท</p>
 <table class="table">
          <thead class="thead-light">
               <thead>
   
  </thead>
              <tr>
                 <th scope="col">ประเภท</th>
                 <th scope="col">รุ่น</th>
                 <th scope="col">ราคาและสถานที่ซื้อ</th>
              </tr>
          </thead>
          
          <tbody>
             <tr>
                <td>CPU</td>
                <td><p><%= micropost.cpu %></p></td>
                <td><p><%= micropost.detail_cpu %></p></td>
             </tr>
              <tr>
                <td>Mainboard</td>
                <td><p><%= micropost.mainboard %></p></td>
                <td><p><%= micropost.detail_mainboard %></p></td>
             </tr>
             
              <tr>
                <td>Ram</td>
                <td><p><%= micropost.ram %></p></td>
                <td><p><%= micropost.detail_ram %></p></td>
             </tr>
             
              <tr>
                <td>Storage</td>
                <td><p><%= micropost.storage %></p></td>
                <td><p><%= micropost.detail_storage %></p></td>
             </tr>
             
              <tr>
                <td>Graphic card</td>
                <td><p><%= micropost.vga %></p></td>
                <td><p><%= micropost.detail_vga %></p></td>
             </tr>
             
              <tr>
                <td>Power</td>
                <td><p><%= micropost.power %></p></td>
                <td><p><%= micropost.detail_power %></p></td>
                
                 <tr>
                <td>Case</td>
                <td><p><%= micropost.case %></p></td>
                <td><p><%= micropost.detail_case %></p></td>
             </tr>
             </tr>
         </tbody>
  </table>

</div>
  
  
  <div style="margin-left: 63px">
    <td><%= link_to raw('<span class="far fa-edit" aria-hidden="true"></span>'), edit_micropost_path(micropost) %></td>  
    <td><%= link_to raw('<span class="far fa-trash-alt" aria-hidden="true"></span>'), micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </div>
  <span class="timestamp" style="margin-left: 0px">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span><br><br>
</li>

app/views/microposts/edit.html.erb
<% provide(:title, "Edit") %>
<main class="main-area">
<h1>Editing Post</h1>

<%= render 'form', micropost: @micropost %>

<%= link_to 'Show', @micropost %> |
<%= link_to raw('<span class="far fa-hand-point-left" aria-hidden="true"> </span> Back'), current_user %>
</main>

app/views/microposts/index.html.erb
<% provide(:title, "All Post") %>
<main class="main-area">
<p id="notice"><%= notice %></p>

<h1>ยินดีต้อนรับ</h1>
<h3>เพราะเงินของคุณมีค่า ให้เราเป็นตัวช่วยในการเลือกอุปกรณ์คอมพิวเตอร์ที่คุ้มค่าที่สุด</h3><br>
<h4>เลือกราคาอุปกรณ์คอมพิวเตอร์ที่น่าสนใจทั้งหมด</h4>

<% if @microposts.count == 0 %>
    <p>"ไม่พบช่วงราคาที่คุณค้นหา"</p>
<% else %>
   
<table id="productSizes" class="table table-striped">
  <thead>
    <tr>
      <th scope="col" style="font-size: 20px;">ราคาที่มีให้คุณเลือกสรรค์</th>
      <th scope="col"> </th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <% @microposts.each do |micropost| %>
        <td style="width:30%"><p style="font-size:1.2em; margin-bottom:0;"><strog>ราคารวม :</strong> <%=micropost.price %> บาท </p>post by: <%=micropost.user.name if micropost.user%>  ||
          <span class="timestamp">
              Posted <%= time_ago_in_words(micropost.created_at) %> ago.<br>
              Update at <%= time_ago_in_words(micropost.updated_at) %> ago.
          </span> </td>
        <td style="width:100%"><br><%= link_to 'view more...', micropost %> </td>
    </tr>
  </tbody>
      <% end %>
<% end %>
<br>
</table>



<%if logged_in?%>
    <%= link_to  raw('<span class="fas fa-plus" aria-hidden="true"> </span> New Post'), posts_path %>
<%end%>
</main>

app/views/microposts/new.html.erb
<% provide(:title, "New Post") %>
<main class="main-area">
    <h1>New Post</h1>

<%= render 'form', micropost: @micropost %>
<%= link_to raw('<span class="far fa-hand-point-left" aria-hidden="true"> </span> Back'), microposts_path %>

</main>

app/views/microposts/show.html.erb
<% provide(:title, @micropost.cpu) %>
<main class="main-area">
<p id="notice"><%= notice %></p>

<h1>Posts</h1>
<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>
<tbody>
   
     <p><strong>ราคารวม :</strong><%= @micropost.price %> บาท</p>
        <table class="table table-striped;col-md-4 col-md-offset-2" style="width: 60%">
          <thead>
              <tr>
                 <th scope="col">ประเภท</th>
                 <th scope="col">รายละเอียด</th>
                 <th scope="col">ราคาและสถานที่ซื้อ</th>
              </tr>
          </thead>
         <tbody>
             <tr >
                <td>CPU</td>
                <td><p><%= @micropost.cpu %></p></td>
                <td><p><%= @micropost.detail_cpu %></p></td>
             </tr>
             
             <tr>
                <td>Mainboard</td>
                <td><p><%= @micropost.mainboard %></p></td>
                <td><p><%= @micropost.detail_mainboard %></p></td>
             </tr>
             
              <tr>
                <td>Ram</td>
                <td><p><%= @micropost.ram %></p></td>
                <td><p><%= @micropost.detail_ram %></p></td>
             </tr>
             
              <tr>
                <td>Storage</td>
                <td><p><%= @micropost.storage %></p></td>
                <td><p><%= @micropost.detail_storage %></p></td>
             </tr>
             
              <tr>
                <td>Graphic card</td>
                <td><p><%= @micropost.vga %></p></td>
                <td><p><%= @micropost.detail_vga %></p></td>
             </tr>
             
              <tr>
                <td>Power</td>
                <td><p><%= @micropost.power %></p></td>
                <td><p><%= @micropost.detail_power %></p></td>
                
                 <tr>
                <td>Case</td>
                <td><p><%= @micropost.case %></p></td>
                <td><p><%= @micropost.detail_case %></p></td>
             </tr>
             </tr>
             
         </tbody>
         
        </table>

         post by: <%=@micropost.user.name%>  ||
            
            <span class="timestamp">
                Posted <%= time_ago_in_words(@micropost.created_at) %> ago.<br>
                Update at <%= time_ago_in_words(@micropost.updated_at) %> ago.
          </span><br>
   
<%if logged_in?%>
    <%if current_user.admin?  %>
        <%= link_to raw('<span class="far fa-edit" aria-hidden="true"></span>'), edit_micropost_path(@micropost) %> | 
        <%= link_to raw('<span class="far fa-trash-alt" aria-hidden="true"></span>'), @micropost, method: :delete, data: { confirm: 'Are you sure?' } %> | 
    <%end%>
<%end%>    
<%= link_to raw('<span class="far fa-hand-point-left" aria-hidden="true"></span> Back'), microposts_path %>

</main>