config/routes.rb
Rails.application.routes.draw do
  
  

  resources :microposts
  root 'static_pages#home'
  get '/about', to:'static_pages#about'
  get '/signup', to: 'users#new'
  post '/signup',to: 'users#create'
  get '/signin', to: 'sessions#new'
  post '/signin', to: 'sessions#create'
  delete '/signout', to: 'sessions#destroy'
  resources :users
  get '/posts',to: 'microposts#new'
  get '/search_all',to: 'microposts#index'
  
end

app/views/layouts/_footer.html.erb
<footer>
    <a name="footer"></a>
    <div class="footer_text">
        <div style="text-align: center;">
            <%= image_tag( "Admin2.png" ,:style => 'float:left;margin-left: 10px;margin-bottom: 20px;') %>
            <h3>Hi, <a href="#">I'm ADMIN</a></h3>

            <p><b style="font-size: 15px"> จัดสเปกคอมคิดถึงเรา
                    เรามีมือโปรในการเลือกชิ้นส่วนอุปกรณ์ที่สามารถดึงประสิทธิภาพของอุปกรณ์แต่ล่ะชิ้นออกมาได้อย่างลงตัว<br>ในราคาที่คุณต้องว้าว
                    ทุกงานบริการของเรามั่นใจได้ว่าคุณจะใช้งานคอมพิวเตอร์ได้อย่างเต็มความสามารถสมกับที่วางใจใช้บริการของเรา</br>
                </b></p>
        </div>
    </div>
    <br>
    <br>
    <br>
    <div class="footer_copyright">
        &copy; 2018 <a href="#">เสปกคอมพิวเตอร์</a> - CN340 <br>
    </div>
</footer>

app/views/layouts/_header.html.erb
 <header class="site-header">
        
        <%= image_tag("egg3.gif", height: '110', width: '110',:style =>'float:right;' ) %>
        <h1 class="topic "style="color: slategray;text-shadow: -1px -1px white, 1px 1px #333;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ผู้ช่วยจัดสเปคคอม ที่ดีที่สุดของคุณ </h1>
        <nav>
            <ul>
               
                <li ><a id="welcome" > <i class="fa fa-id-card" aria-hidden="true"></i> ยินดีต้อนรับ</li>
                <li><%= link_to raw('<span class="fa fa-home" aria-hidden="true"></span> Home'), root_path%></li>
                <li><%= link_to raw('<span class="fab fa-angellist" aria-hidden="true"></span> About'), about_path %></li>
                <li><%= link_to raw('<span class= "fas fa-clipboard aria-hidden="true"></span> All Post'),search_all_path %></li>
                
                <% if logged_in? %>
                  
                  <li><%= link_to raw('<span class="fas fa-plus" aria-hidden="true"></span> New Post'), posts_path %></li>
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu">
                      <li><%= link_to "My Post", current_user %></li>
                      
                      <li class="divider"></li>
                      <li>
                          <%= link_to raw('<span class="fas fa-sign-out-alt" aria-hidden="true"></span> Sign out'), signout_path,:method => :delete%>
                      </li>
                      
                    </ul>
                  </li>
                <% else %>
                  <li><%= link_to raw('<span class="fas fa-sign-in-alt" aria-hidden="true"></span> Sign in'),signin_path %></li>
                  <li><%= link_to raw('<span class="fa fa-key" aria-hidden="true"></span> Sign up'), signup_path %></li>
                <% end %>
    
            </ul>
        </nav>
        

    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_tile(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Inconsolata|Kalam" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Taviraj:300" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Athiti" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
  <!--<link href="assets/stylesheet/static_pages.scss" rel="stylesheet" >-->
  <style>
     .contain{
       
        margin: auto;
        padding: 20px;
        width: 900px;
        /*height: 1998px;*/
        border:20px;
        border-color:; #ffaa77;
        background-color:cornsilk;
        font-family: "Short Stack";
       
        
    }
    .bg-faded {
  background-color: palegoldenrod;
 
    }
    .card {
  position: relative;
  display: -ms-flexbox;
  display: flex;
  -ms-flex-direction: column;
      flex-direction: column;
  min-width: 0;
  word-wrap: break-word;
  /*background-color: gainsboro;*/ 
  background-clip: border-box;
  border: 1px solid rgba(0, 0, 0, 0.125);
  border-radius: 0.25rem;
  padding:20px;
}
/*.card-img-overlay {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  padding: 1.25rem;
}*/
.bg-overlay {
  background-color: rgba(0, 0, 0, 0.7);
}
.tablebox{
    padding:20px;
}

  </style>

</head>
  <body>
     <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <div class = "container">
      
     
  
      <%= render 'layouts/header' %>
      
      <%= yield %>
      
      <%= render 'layouts/footer' %>
      
    </div>
    <!-- <%= debug(params) if Rails.env.development? %>   -->
  </body>
</html>